let vocab=[];
let coins=0,energy=0,cardIndex=0,known=0,question=1,sessionCoins=0,mode='engvi',answered=false;
const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);
function format(n){return n.toLocaleString('en-US')}
function updateCoins(){['#coinCount','#shopCoins'].forEach(s=>$(s).textContent=format(coins))}
async function syncProfile(extra={}){if(window.studyStore?.connected()&&window.studyStore.user)try{await window.studyStore.saveProfile({coins,energy,streak:0,knownWords:known,totalWords:vocab.length,...extra})}catch(e){console.warn('Firebase sync:',e)}}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2400)}
function showPage(id){$$('.page').forEach(p=>p.classList.remove('active-page'));$('#'+id).classList.add('active-page');$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.page===id));$('.sidebar').classList.remove('open');if(id==='ranking')renderLeaderboard();window.scrollTo({top:0,behavior:'smooth'})}
$$('.nav-item').forEach(b=>b.onclick=()=>showPage(b.dataset.page));$$('[data-go]').forEach(b=>b.onclick=()=>showPage(b.dataset.go));$('.start-lesson').onclick=()=>showPage('learn');$('.menu-toggle').onclick=()=>$('.sidebar').classList.toggle('open');
function renderWordList(){const list=$('#wordList');list.innerHTML=vocab.length?vocab.map((v,i)=>`<button class="word-item ${i===cardIndex?'selected':''}" data-index="${i}">${v.word}<small>${v.pron||'Chưa có phiên âm'}</small>${i<known?'<i>✓</i>':''}</button>`).join(''):'<p class="empty-state">Chưa có từ nào.</p>';$$('.word-item').forEach(b=>b.onclick=()=>{cardIndex=+b.dataset.index;renderCard()});['#wordListCount','#totalWords','#cardTotal'].forEach(s=>$(s).textContent=vocab.length)}
function renderCard(){if(!vocab.length){$('#cardWord').textContent='Chưa có từ vựng';$('#cardPronounce').textContent='Hãy thêm từ đầu tiên của bạn';$('#cardMeaning').innerHTML='Kat đang<br>chờ bạn!';$('.card-front .card-visual').textContent='🐱';$('#cardStep').textContent='00';renderWordList();return}const v=vocab[cardIndex%vocab.length];$('#cardWord').textContent=v.word;$('#cardPronounce').textContent=v.pron||'—';$('#cardMeaning').innerHTML=v.mean.replace(' ','<br>');$('.card-front .card-visual').textContent=v.emoji;$('#cardStep').textContent=String(cardIndex+1).padStart(2,'0');$('.flashcard').classList.remove('flipped');renderWordList()}
$('#flashcard').onclick=()=>{if(vocab.length)$('#flashcard').classList.toggle('flipped')};$('#prevCard').onclick=()=>{if(!vocab.length)return;cardIndex=(cardIndex+vocab.length-1)%vocab.length;renderCard()};$('#nextCard').onclick=()=>{if(!vocab.length)return;cardIndex=(cardIndex+1)%vocab.length;renderCard()};$('#knowBtn').onclick=()=>{if(!vocab.length)return toast('Hãy thêm từ vựng trước nhé!');known=Math.min(vocab.length,known+1);$('#knownCount').textContent=known;syncProfile();toast('Đã ghi nhận! Bạn đang tiến bộ rất tốt ✨');cardIndex=(cardIndex+1)%vocab.length;renderCard()};
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
async function loadAiContext(v){const fallback=`I <b>${v.word}</b> is a useful word to practise every day.`;$('#questionWord').innerHTML=fallback;try{const res=await fetch('/api/context-example',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({word:v.word,meaning:v.mean})});const data=await res.json();if(res.ok&&data.text)$('#questionWord').innerHTML=data.text.replace(/\n/g,'<br>');else $('#questionHint').textContent='AI chưa được cấu hình — dùng câu ví dụ mặc định:'}catch(e){$('#questionHint').textContent='AI chỉ hoạt động khi chạy server — dùng câu ví dụ mặc định:'}}
function renderQuiz(){answered=false;if(!vocab.length){$('#questionHint').textContent='Bạn cần thêm từ vựng trước khi luyện tập.';$('#questionWord').textContent='Chưa có bộ từ';$('#questionPronounce').textContent='';$('#answers').innerHTML='<button class="answer" id="goAddWords"><b>＋</b> Thêm từ vựng ngay</button>';$('#goAddWords').onclick=()=>showPage('learn');$('#feedback').textContent='';return}const v=vocab[(question-1)%vocab.length];let correct,answers,hint,word,pron='';if(mode==='engvi'){hint='Chọn nghĩa tiếng Việt của từ:';word=v.word;pron=v.pron;correct=v.mean;answers=shuffle(vocab.map(x=>x.mean))}else if(mode==='vieng'){hint='Chọn từ tiếng Anh phù hợp với nghĩa:';word=v.mean;correct=v.word;answers=shuffle(vocab.map(x=>x.word))}else{hint='Từ in đậm trong ngữ cảnh có nghĩa là gì?';word=`I <b>${v.word}</b> is a useful word to practise every day.`;correct=v.mean;answers=shuffle(vocab.map(x=>x.mean));}
 $('#questionHint').textContent=hint;$('#questionWord').innerHTML=word;$('#questionPronounce').textContent=pron;$('#questionNumber').textContent=question;$('#quizProgress').style.width=question*10+'%';const labels=['A','B','C','D','E'];$('#answers').innerHTML=answers.slice(0,4).map((a,i)=>`<button class="answer" data-right="${a===correct}"><b>${labels[i]}</b>${a}</button>`).join('');if(!answers.slice(0,4).includes(correct)){$('#answers').lastElementChild.innerHTML=`<b>D</b>${correct}`;$('#answers').lastElementChild.dataset.right='true'}$('#feedback').textContent='';$$('.answer').forEach(btn=>btn.onclick=()=>answer(btn,correct));if(mode==='context')loadAiContext(v);}
function answer(btn,correct){if(answered)return;answered=true;const good=btn.dataset.right==='true',v=vocab[(question-1)%vocab.length];$$('.answer').forEach(b=>{if(b.dataset.right==='true')b.classList.add('correct')});if(good){sessionCoins+=10;coins+=10;energy+=10;updateCoins();syncProfile();$('#sessionCoins').textContent=sessionCoins;$('#feedback').textContent='Chính xác! +10 xu 🪙'}else{btn.classList.add('wrong');$('#feedback').textContent=`Đáp án đúng là: ${correct}`;$('#feedback').style.color='#e36b63'}window.studyStore?.recordAnswer({word:v.word,meaning:v.mean,mode,correct:good,reviewDueAt:Date.now()+30*24*60*60*1000});setTimeout(()=>{if(question>=10){$('#reward').textContent=`+${sessionCoins} 🪙`;$('#resultModal').classList.add('show');question=1;sessionCoins=0;$('#sessionCoins').textContent='0'}else{question++;renderQuiz()}},900)}
$$('.mode-card').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;$$('.mode-card').forEach(x=>x.classList.toggle('active-mode',x===b));question=1;renderQuiz()});$('.close-modal').onclick=()=>{$('#resultModal').classList.remove('show');renderQuiz()};
$$('.shop-grid button').forEach((b,i)=>b.onclick=()=>{const price=+b.dataset.price;if(coins>=price){coins-=price;updateCoins();syncProfile();window.studyStore?.purchase({id:`item-${i+1}`,name:b.closest('article').querySelector('h3').textContent,price});b.textContent='✓ Đã mua';b.disabled=true;toast('Đã thêm vật phẩm vào bộ sưu tập!')}else toast('Bạn chưa đủ xu cho vật phẩm này.')});
$('#addWordBtn').onclick=()=>$('#wordModal').classList.add('show');$('#closeWordModal').onclick=()=>$('#wordModal').classList.remove('show');$('#wordModal').onclick=e=>{if(e.target===$('#wordModal'))$('#wordModal').classList.remove('show')};$('#wordForm').onsubmit=e=>{e.preventDefault();const item={word:$('#newWord').value.trim(),mean:$('#newMeaning').value.trim(),pron:$('#newPronounce').value.trim(),emoji:$('#newEmoji').value};if(vocab.some(v=>v.word.toLowerCase()===item.word.toLowerCase()))return toast('Từ vựng này đã có trong danh sách.');vocab.push(item);localStorage.setItem('katlearn-vocab',JSON.stringify(vocab));cardIndex=vocab.length-1;$('#wordForm').reset();$('#wordModal').classList.remove('show');renderCard();renderQuiz();syncProfile();toast(`Đã thêm “${item.word}” vào bộ từ của bạn!`)};
function esc(text){return String(text||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
async function renderLeaderboard(){const target=$('#rankingContent'),mini=$('#miniRanking');if(!window.studyStore?.user){const note='Đăng nhập để xem bảng xếp hạng thực tế. 🐱';target.textContent=note;mini.textContent='Đăng nhập và học để xuất hiện trên bảng xếp hạng. 🐾';return}try{const users=await window.studyStore.leaderboard();if(!users.length){target.textContent='Chưa có thành tích nào. Hãy là người đầu tiên học cùng Kat! 🐾';mini.textContent='Chưa có thành tích nào.';return}const rows=users.map((u,i)=>`<div class="rank-list-row ${u.id===window.studyStore.userId?'mine':''}"><b>${String(i+1).padStart(2,'0')}</b><span class="rank-avatar">${esc((u.displayName||'K')[0]).toUpperCase()}</span><strong>${esc(u.displayName||'KatLearn Student')}</strong><small>⚡ ${Number(u.energy||0).toLocaleString('en-US')} năng lượng</small><i>🪙 ${Number(u.coins||0).toLocaleString('en-US')}</i></div>`).join('');target.innerHTML=rows;mini.innerHTML=users.slice(0,3).map((u,i)=>`<div class="rank-row"><b>${String(i+1).padStart(2,'0')}</b><span class="rank-avatar">${esc((u.displayName||'K')[0]).toUpperCase()}</span><strong>${esc(u.displayName||'KatLearn Student')}</strong><span>⚡ ${Number(u.energy||0)}</span></div>`).join('')}catch(e){target.textContent='Chưa thể tải bảng xếp hạng.';mini.textContent='Chưa thể tải bảng xếp hạng.'}}
async function renderPublicPacks(){const target=$('#publishedPacks'),adminList=$('#publicPackList');if(!window.studyStore?.user){target.textContent='Đăng nhập để xem các pack từ vựng công khai.';return}try{const packs=await window.studyStore.publicPacks();const body=packs.length?packs.map(pack=>`<div class="published-pack"><span>📚</span><div><b>${esc(pack.name)}</b><small>${pack.words.length} từ vựng</small></div><button data-pack="${pack.id}">Học pack</button></div>`).join(''):'<div class="empty-state">Chưa có pack công khai.</div>';target.innerHTML=`<b>Pack từ vựng công khai</b>${body}`;if(adminList)adminList.innerHTML=body;$$('[data-pack]').forEach(btn=>btn.onclick=()=>{const pack=packs.find(p=>p.id===btn.dataset.pack);vocab=pack.words;known=0;cardIndex=0;renderCard();renderQuiz();showPage('learn');toast(`Đã tải pack “${pack.name}”.`)});}catch(e){target.textContent='Chưa thể tải pack công khai.';if(adminList)adminList.textContent='Chưa thể tải danh sách pack.'}}
function renderAdmin(user){const canAdmin=!!user&&window.studyStore.isAdmin();$('.admin-nav').hidden=!canAdmin;if(!canAdmin&&$('#admin').classList.contains('active-page'))showPage('home')}
$('#publicPackForm').onsubmit=async e=>{e.preventDefault();if(!window.studyStore.isAdmin())return toast('Tài khoản này chưa có quyền admin.');const lines=$('#publicPackWords').value.split('\n').map(x=>x.trim()).filter(Boolean),words=[];for(const line of lines){const [word,mean,pron='']=line.split('|').map(x=>x.trim());if(word&&mean)words.push({word,mean,pron,emoji:'📚'})}if(!words.length)return toast('Mỗi dòng cần có: English | Nghĩa tiếng Việt');try{await window.studyStore.createPublicPack({name:$('#publicPackName').value.trim(),words});$('#publicPackForm').reset();await renderPublicPacks();toast('Đã xuất bản pack công khai!')}catch(err){toast('Không thể xuất bản: '+err.message)}};$('#copySecretCommand').onclick=async()=>{try{await navigator.clipboard.writeText('firebase functions:secrets:set OPENAI_API_KEY');toast('Đã sao chép lệnh Firebase Secret.')}catch(e){toast('Hãy sao chép lệnh hiển thị bên trên.')}};
const savedFirebase=localStorage.getItem('8b1-firebase-config'),defaultFirebase=window.KATLEARN_FIREBASE_CONFIG;const firebaseConfig=savedFirebase?JSON.parse(savedFirebase):defaultFirebase;$('#firebaseConfig').value=JSON.stringify(firebaseConfig,null,2);window.studyStore.connect(firebaseConfig).then(()=>syncProfile()).catch(e=>console.warn('Firebase chưa kết nối:',e));$('#settingsBtn').onclick=()=>$('#settingsModal').classList.add('show');$('#closeSettingsModal').onclick=()=>$('#settingsModal').classList.remove('show');$('#settingsModal').onclick=e=>{if(e.target===$('#settingsModal'))$('#settingsModal').classList.remove('show')};$('#settingsForm').onsubmit=async e=>{e.preventDefault();try{const config=JSON.parse($('#firebaseConfig').value);await window.studyStore.connect(config);localStorage.setItem('8b1-firebase-config',JSON.stringify(config));await syncProfile();$('#settingsModal').classList.remove('show');toast('Đã kết nối Firebase và bắt đầu đồng bộ dữ liệu!')}catch(err){toast('Firebase config không hợp lệ: '+err.message)}};
function renderAuth(user){const btn=$('#loginBtn');btn.textContent=user?'Đăng xuất':'Đăng nhập';btn.classList.toggle('logged-in',!!user);btn.onclick=async()=>{if(user){await window.studyStore.signOut();toast('Đã đăng xuất.')}else $('#loginModal').classList.add('show')}}
window.addEventListener('8b1-auth-change',e=>{renderAuth(e.detail);renderAdmin(e.detail);if(e.detail){syncProfile();renderLeaderboard();renderPublicPacks()}});renderAuth(null);renderAdmin(null);$('#closeLoginModal').onclick=()=>$('#loginModal').classList.remove('show');$('#loginModal').onclick=e=>{if(e.target===$('#loginModal'))$('#loginModal').classList.remove('show')};async function providerLogin(provider){try{const user=await window.studyStore.signIn(provider);$('#loginModal').classList.remove('show');renderAuth(user);toast(`Chào mừng ${user.displayName||'bạn'}! Dữ liệu đang được đồng bộ.`)}catch(err){toast('Không thể đăng nhập: '+err.message)}}$('#googleLogin').onclick=()=>providerLogin('google');$('#appleLogin').onclick=()=>providerLogin('apple');
renderCard();renderQuiz();updateCoins();
